# Generated by Django 4.1.3 on 2022-11-21 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prop_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_status', models.CharField(max_length=20)),
                ('prop_status_descr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_type_name', models.CharField(max_length=30)),
                ('prop_type_descr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdiv_name', models.CharField(max_length=50)),
                ('subdiv_descr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('postal', models.IntegerField()),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=500)),
                ('bathroom_count', models.FloatField(max_length=250)),
                ('bedroom_count', models.IntegerField()),
                ('square_footage', models.IntegerField()),
                ('visible', models.BooleanField()),
                ('featured', models.BooleanField()),
                ('prop_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.prop_status')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.property_type')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subdivision')),
            ],
        ),
    ]
